version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}
    command: sleep infinity
    depends_on:
      - db
    environment:
      # Rails sees Postgres on the "db" service name
      DATABASE_URL: postgres://postgres:postgres@db:5432/app_development
    ports:
      - "3000:3000"
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

