default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:postgres@localhost:5432/app_development") %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:postgres@localhost:5432/app_test") %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
